#!/bin/sh
PATH=/var/jb/usr/bin:/var/jb/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH
case "$1" in remove|upgrade|deconfigure)
  launchctl bootout system/com.applelive.uvchost >/dev/null 2>&1 || true
  ;;
esac
exit 0
